<a href="https://colab.research.google.com/github/arnautoleg/DATA-SCIENCE/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# ТИПЫ ДАННЫХ

In [4]:
#Какие минимальное и максимальное числа можно сохранить в 16 бит?

print(2**16/2 - 1)
print(-2**16/2)


32767.0
-32768.0


In [10]:
import numpy as np
a = np.int8(25)
print(a)
# 25

25


In [11]:
print(type(a))
# <class 'numpy.int8'>

<class 'numpy.int8'>


In [17]:
# Можно применить к самому
# названию типа данных
print(np.iinfo(np.int64))
# iinfo(min=-128, max=127, dtype=int8)

# Можно применить к существующему
# конкретному объекту
print(np.iinfo(a))
# iinfo(min=-128, max=127, dtype=int8)

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------



In [18]:
b = np.uint8(124)
print(b)
# 124
print(type(b))
# <class 'numpy.uint8'>
np.iinfo(b)
# iinfo(min=0, max=255, dtype=uint8)

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [25]:
b = np.uint8(-456)
print(b)
# 124
print(type(b))
# <class 'numpy.uint8'>
np.iinfo(b)
# iinfo(min=0, max=255, dtype=uint8)

56
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [19]:
np.finfo(np.float16)
# finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)
np.finfo(np.float32)
# finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
np.finfo(np.float64)
# finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)
np.finfo(np.float128)
# finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

In [20]:
print(np.sctypeDict)
print(len(np.sctypeDict))
# 158, но может быть 135 или 139

{'?': <class 'numpy.bool_'>, 0: <class 'numpy.bool_'>, 'byte': <class 'numpy.int8'>, 'b': <class 'numpy.int8'>, 1: <class 'numpy.int8'>, 'ubyte': <class 'numpy.uint8'>, 'B': <class 'numpy.uint8'>, 2: <class 'numpy.uint8'>, 'short': <class 'numpy.int16'>, 'h': <class 'numpy.int16'>, 3: <class 'numpy.int16'>, 'ushort': <class 'numpy.uint16'>, 'H': <class 'numpy.uint16'>, 4: <class 'numpy.uint16'>, 'i': <class 'numpy.int32'>, 5: <class 'numpy.int32'>, 'uint': <class 'numpy.uint64'>, 'I': <class 'numpy.uint32'>, 6: <class 'numpy.uint32'>, 'intp': <class 'numpy.int64'>, 'p': <class 'numpy.int64'>, 7: <class 'numpy.int64'>, 'uintp': <class 'numpy.uint64'>, 'P': <class 'numpy.uint64'>, 8: <class 'numpy.uint64'>, 'long': <class 'numpy.int64'>, 'l': <class 'numpy.int64'>, 'ulong': <class 'numpy.uint64'>, 'L': <class 'numpy.uint64'>, 'longlong': <class 'numpy.longlong'>, 'q': <class 'numpy.longlong'>, 9: <class 'numpy.longlong'>, 'ulonglong': <class 'numpy.ulonglong'>, 'Q': <class 'numpy.ulonglo

# Модуль NumPy. Массивы

Итак, массив — это структура данных, в которой:

1
Элементы хранятся в указанном порядке.

2
Каждый элемент можно получить по индексу за одинаковое время.

3
Все элементы приведены к одному и тому же типу данных.

4
Максимальное число элементов и объём выделенной памяти заданы заранее.

In [26]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr
# array([ 1,  5,  2,  9, 10])

array([ 1,  5,  2,  9, 10])

In [27]:
print(type(arr))
# <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [28]:
# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr
# array([[12, 45, 78],
#        [34, 56, 13],
#        [12, 98, 76]])

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [29]:
arr = np.array([1,5,2,9,10])
arr.dtype
# dtype('int64')

dtype('int64')

In [30]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr
# array([ 1,  5,  2,  9, 10], dtype=int8)

array([ 1,  5,  2,  9, 10], dtype=int8)

In [31]:
arr[2] = 2000
arr
# array([  1,   5, -48,   9,  10], dtype=int8)

array([  1,   5, -48,   9,  10], dtype=int8)

# СВОЙСТВА NUMPY-МАССИВОВ

In [32]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

## Узнать размерность массива можно с помощью .ndim:

In [33]:
arr.ndim
# 1
nd_arr.ndim
# 2

2

## Узнать общее число элементов в массиве можно с помощью .size:

In [34]:
arr.size
# 5
nd_arr.size
# 9

9

## Форма или структура массива хранится в атрибуте .shape:

In [35]:
arr.shape
# (5,)
nd_arr.shape
# (3, 3)

(3, 3)

## Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:

In [36]:
arr.itemsize
# 1
nd_arr.itemsize
# 2

2

# ЗАПОЛНЕНИЕ НОВЫХ МАССИВОВ

In [37]:
zeros_1d = np.zeros(5)
zeros_1d
# array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

In [38]:
zeros_1d.itemsize

8

In [39]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
# (5, 4, 3)

(5, 4, 3)


In [40]:
zeros_3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [41]:
np.arange(5)
# array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [42]:
np.arange(2.5, 5)
# array([2.5, 3.5, 4.5])

array([2.5, 3.5, 4.5])

In [44]:
np.arange(2.5, 5, 1)
# array([2.5, 3. , 3.5, 4. , 4.5])

array([2.5, 3.5, 4.5])

In [45]:
np.arange(2.5, 5, 0.5, dtype=np.float16)
# array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

## np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;

num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);

endpoint — включён или исключён конец диапазона (по умолчанию включён);

retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;

dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).

In [46]:
arr = np.linspace(1, 2, 10)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [47]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr
# array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [48]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
# 0.1

0.1111111111111111
0.1


In [49]:
arr, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111

arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)
# 0.1

0.4576271186440678
0.45


# Модуль NumPy. Действия с массивами

In [55]:
import numpy as np
arr = np.arange(8)
arr
# array([0, 1, 2, 3, 4, 5, 6, 7])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [59]:
arr.shape = (2, 2, 2)
#arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [60]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new
# array([[0, 1, 2, 3],
#       [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
# У функции reshape есть дополнительный именованный аргумент order.
# Он задаёт принцип, по которому элементы заполняют массив новой формы.
# Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше.
# Если order='F', массив заполняется числами по столбцам:

arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new
# array([[0, 2, 4, 6],
#       [1, 3, 5, 7]])

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [67]:
arr = np.arange(8)
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [69]:
arr_trans = arr.transpose()
arr_trans
# array([[0, 4],
#        [1, 5],
#        [2, 6],
#        [3, 7]])

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

# ИНДЕКСЫ И СРЕЗЫ В МАССИВАХ

In [70]:
arr = np.linspace(1, 2, 6)
arr
# array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [71]:
print(arr[2])
# 1.4

1.4


In [72]:

print(arr[2:4])
# [1.4 1.6]


[1.4 1.6]


In [73]:
print(arr[::-1])
# [2.  1.8 1.6 1.4 1.2 1. ]

[2.  1.8 1.6 1.4 1.2 1. ]


In [74]:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array
# array([[0. , 0.5, 1. , 1.5],
#        [2. , 2.5, 3. , 3.5],
#        [4. , 4.5, 5. , 5.5]])

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [75]:
nd_array[1][2]
# 3.0

3.0

In [76]:
nd_array[1, 2]
# 3.0

3.0

In [77]:
nd_array[:2, 2]
# array([1., 3.])

array([1., 3.])

In [78]:
nd_array[1:, 2:4]
# array([[3. , 3.5],
#       [5. , 5.5]])

array([[3. , 3.5],
       [5. , 5.5]])

In [79]:
nd_array[:, 2:4]
# array([[1. , 1.5],
#       [3. , 3.5],
#       [5. , 5.5]])

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [80]:
nd_array[:2]
# array([[0. , 0.5, 1. , 1.5],
#       [2. , 2.5, 3. , 3.5]])

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [81]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
                    [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
                    [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
                    [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
                    [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
                    [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
                     dtype=np.int16)

In [91]:
elem_5_3 = mystery[4, 2]
print(elem_5_3)
last = mystery[-1, -1]
print(last)
line_4 = mystery[3]
print(line_4)
col_2 = mystery[:, -2]
print(col_2)
part = mystery[1:4, 2:5]
print(part)
rev = mystery[:, -1]
rev = rev[::-1]
print(rev)
trans = mystery.transpose()
print(trans)


30305
-32037
[13240  7994 32592 20149 13754 11795  -564]
[-17182  15790  25397  11795  12578    -47]
[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]
[-32037  29943   -564   8225   7181 -18049]
[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


## СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ

In [92]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
# [23 12 45 12 23  4 15  3]
print(arr_new)
# [ 3  4 12 12 15 23 23 45]

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [94]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)
# [ 3  4 12 12 15 23 23 45]

None
[ 3  4 12 12 15 23 23 45]


## РАБОТА С ПРОПУЩЕННЫМИ ДАННЫМИ

In [95]:
data = np.array([4, 9, -4, 3])

In [96]:
roots = np.sqrt(data)
roots
# RuntimeWarning: invalid value encountered in sqrt
# array([2.        , 3.        ,        nan, 1.73205081])

<ipython-input-96-b84b0d3d488d>:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [98]:
# Отличие 1. None является отдельным объектом типа NoneType.
# np.nan — это отдельный представитель класса float:

print(type(None))
# <class 'NoneType'>
print(type(np.nan))
# <class 'float'>
type(np.nan)


<class 'NoneType'>
<class 'float'>


float

In [99]:
# Отличие 2. None могут быть равны друг другу, а np.nan — нет:

print(None == None)
# True
print(np.nan == np.nan)
# False


True
False


In [100]:
# Как вы помните, чтобы грамотно сравнить что-либо с None, необходимо использовать оператор is.
# Это ещё более актуально для np.nan.
# Однако None даже через is не является эквивалентным np.nan:

print(None is None)
# True
print(np.nan is np.nan)
# True
print(np.nan is None)
# False


True
True
False


In [101]:
sum(roots)
# nan


nan

In [102]:
np.isnan(roots)
# array([False, False,  True, False])


array([False, False,  True, False])

In [103]:
roots[np.isnan(roots)]
# array([nan])

array([nan])

In [104]:
roots[np.isnan(roots)] = 0
roots
# array([2.        , 3.        , 0.        , 1.73205081])

array([2.        , 3.        , 0.        , 1.73205081])

In [105]:
sum(roots)
# 6.732050807568877

6.732050807568877

In [152]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
                     -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
                     29810.], dtype=np.float32)

In [156]:
from collections import Counter

nans_index = np.isnan(mystery)
print(nans_index)

n_nan = Counter(nans_index)[1]
print(n_nan)

mystery_int = np.array(mystery, dtype=np.int32)
print(mystery_int)

array = np.sort(mystery)
print(array)

table = array.reshape((5, 3), order='F')
print(table)

mystery_new = mystery.copy()

mystery_new[np.isnan(mystery_new)] = 0
print(mystery_new)

col=table[:, -2]
print(col)




[False False False  True False False False False  True False False False
  True False False]
3
[      12279      -26024       28745 -2147483648       31244       -2365
       -6974       -9212 -2147483648      -17722       16132       25933
 -2147483648      -16431       29810]
[-26024. -17722. -16431.  -9212.  -6974.  -2365.  12279.  16132.  25933.
  28745.  29810.  31244.     nan     nan     nan]
[[-26024.  -2365.  29810.]
 [-17722.  12279.  31244.]
 [-16431.  16132.     nan]
 [ -9212.  25933.     nan]
 [ -6974.  28745.     nan]]
[ 12279. -26024.  28745.      0.  31244.  -2365.  -6974.  -9212.      0.
 -17722.  16132.  25933.      0. -16431.  29810.]
[-2365. 12279. 16132. 25933. 28745.]


array([[-26024.,  -2365.,  29810.],
       [-17722.,  12279.,  31244.],
       [-16431.,  16132.,     nan],
       [ -9212.,  25933.,     nan],
       [ -6974.,  28745.,     nan]], dtype=float32)

# Модуль NumPy. Операции с векторами

In [157]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2
# array([14. , 10. , 10.6, 15.5])

array([14. , 10. , 10.6, 15.5])

In [159]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2
# [2, 4, 7, 2.5, 12, 6, 3.6, 13]

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [160]:
[x + y for x, y in zip(list1, list2)]
# [14, 10, 10.6, 15.5]

[14, 10, 10.6, 15.5]

In [161]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2
# array([24. , 24. , 25.2, 32.5])

array([24. , 24. , 25.2, 32.5])

In [162]:
vec = np.arange(5)
vec * 10
# array([ 0, 10, 20, 30, 40])
vec ** 2
# array([ 0,  1,  4,  9, 16])

array([ 0,  1,  4,  9, 16])

In [163]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 > vec2
# array([False, False,  True, False])

array([False, False,  True, False])

In [164]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26
# array([ True,  True,  True,  True, False,  True, False])

array([ True,  True,  True,  True, False,  True, False])

## ПРОДВИНУТЫЕ ОПЕРАЦИИ С ВЕКТОРАМИ

In [165]:
# Длина
vec = np.array([3, 4])
length = np.sqrt(np.sum(vec ** 2))
print(length)
# 5.0

5.0


In [166]:
length = np.linalg.norm(vec)
print(length)
# 5.0

5.0


In [167]:
# Расстояние
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance
# 12.206555615733702

12.206555615733702

In [168]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance
# 12.206555615733702

12.206555615733702

In [169]:
# Cкалярное произведение
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product
# 250.0

250.0

In [170]:
scalar_product = np.dot(vec1, vec2)
scalar_product
# 250.0

250.0

In [171]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)
# 0  (вектора перпендикулярны)

0

# Модуль NumPy. Случайные числа

In [172]:
# Самой «базовой» функцией в нём можно считать функцию rand.
# По умолчанию она генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно):

import numpy as np
np.random.rand()
# 0.06600758835806675


0.3209655187562209

In [173]:
np.random.rand(5)
# array([0.83745099, 0.58426808, 0.89206204, 0.41149807, 0.42445145])

array([0.76634585, 0.45511409, 0.29536614, 0.45930989, 0.53817895])

In [176]:
np.random.rand(2, 3)
# array([[0.94931212, 0.06680018, 0.26707599],
#      [0.67908873, 0.18001743, 0.97732239]])

array([[29.80201633, 82.27453063, 29.9700639 ],
       [43.91911559, 77.28966004, 90.81458069]])

In [175]:
np.random.rand(2, 3, 4, 10, 12, 23)

array([[[[[[3.04234684e-01, 8.94071751e-01, 6.68190269e-01, ...,
            3.12093730e-01, 9.31722221e-01, 9.41510478e-01],
           [6.38497513e-01, 8.04582353e-01, 8.91346805e-01, ...,
            1.23996312e-01, 8.58035463e-01, 2.78363750e-01],
           [2.05851901e-01, 1.90262250e-01, 6.90692277e-02, ...,
            2.14364269e-01, 3.98650113e-01, 1.15037599e-01],
           ...,
           [5.71280468e-01, 4.83688749e-01, 4.84022459e-01, ...,
            1.67916262e-02, 9.15815547e-01, 7.87125537e-01],
           [8.56038130e-01, 4.92320150e-01, 8.66486168e-01, ...,
            8.92943754e-01, 1.16445470e-01, 4.73844276e-01],
           [9.05580930e-01, 1.43313944e-01, 2.70061411e-01, ...,
            4.57068609e-02, 5.31862635e-01, 1.73249631e-01]],

          [[4.10516434e-01, 9.51477914e-02, 9.22498871e-01, ...,
            8.14507725e-01, 6.87092221e-01, 5.63599320e-01],
           [6.06875544e-01, 2.24264819e-01, 5.69321319e-01, ...,
            3.89765581e-01, 9.96831

In [177]:
shape = (2, 3)
np.random.sample(shape)
# array([[0.39756103, 0.01995168, 0.2768951 ],
#       [0.82195372, 0.26435273, 0.00957881]])

array([[0.39007868, 0.04395445, 0.78091427],
       [0.93230872, 0.7211994 , 0.94135126]])

In [179]:
! pip install uniform

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/70.3 kB 4.3 MB/s eta 0:00:00


In [181]:
import uniform

uniform(low=0.0, high=1.0, size=None)
np.random.uniform()
# 0.951557685543591

TypeError: 'module' object is not callable

In [182]:
# Получим пять чисел в интервале от 0.5 до 0.75:

np.random.uniform(0.5, 0.75, size=5)
# array([0.58078945, 0.58860342, 0.73790553, 0.63448265, 0.70920297])

array([0.65601692, 0.55238142, 0.50157984, 0.69393872, 0.61350476])

In [183]:
# Получим массив из двух строк и трёх столбцов из чисел в интервале от -1000 до 500:

np.random.uniform(-1000, 500, size=(2, 3))
# array([[ 129.22164163,   77.69090611, -132.9656972 ],
#        [  18.65802226, -317.14793906,   85.3613547 ]])

array([[ 3.53020698e+02,  4.81917838e+02,  6.83966985e-01],
       [-9.15298422e+02, -6.71835168e+02,  1.97024406e+02]])

## ГЕНЕРАЦИЯ INT

randint(low, high=None, size=None, dtype=int)

Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.

Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).

size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.

dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.

In [184]:
np.random.randint(4, size=(2,3))
# array([[3, 0, 1],
#       [2, 1, 3]])

array([[2, 1, 3],
       [3, 2, 2]])

In [185]:
np.random.randint(6, 12, size=(3,3))
# array([[ 9,  6, 10],
#        [10, 11, 10],
#        [ 7, 10, 11]])

array([[ 9,  7,  7],
       [ 7,  6,  8],
       [ 6, 10, 10]])

## ГЕНЕРАЦИЯ ВЫБОРОК

Просто перемешать все числа в массиве позволяет функция random.shuffle.


Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation. Она принимает на вход один аргумент — или массив целиком, или одно число:


Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n), где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.


Чтобы получить случайный набор объектов из массива, используется функция random.choice:

In [186]:
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])

[0 1 2 3 4 5]
None


array([4, 3, 0, 2, 5, 1])

In [187]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

['ACDC' 'The Beatles' 'Deep Purple' 'Pink Floyd']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [189]:
np.random.permutation(10)
# array([7, 8, 2, 9, 4, 3, 1, 0, 5, 6])

array([2, 1, 9, 3, 7, 4, 6, 0, 5, 8])

In [ ]:
#choice(a, size=None, replace=True)

#a — одномерный массив или число для генерации arange(a);
#size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
#replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).


In [190]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']

choice = np.random.choice(workers, size=2, replace=False)
print(choice)


['Nikita' 'Ivan']


In [200]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice.mean())
# [3 5 5 6 6 4 2 2 1 3]

3.4997842


## SEED ГЕНЕРАТОРА ПСЕВДОСЛУЧАЙНЫХ ЧИСЕЛ

In [203]:
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [207]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]
